@Echo OFF
Echo Generating setups...
Echo Atic Atac setup...
"C:\Program files (x86)\Inno Setup 6\iscc" ".\AticAtac\AticAtac.iss"
Echo Sabrewulf setup...
"C:\Program files (x86)\Inno Setup 6\iscc" ".\Sabrewulf\Sabrewulf.iss"
Echo 3inarow setup...
"C:\Program files (x86)\Inno Setup 6\iscc" ".\3inarow\3inarow.iss"
Echo DragonWindII setup...
"C:\Program files (x86)\Inno Setup 6\iscc" ".\DragonWindII\DragonWindII.iss"
Echo BattleshipII setup...
"C:\Program files (x86)\Inno Setup 6\iscc" ".\BattleshipII\BattleshipII.iss"
Echo PacManII setup...
"C:\Program files (x86)\Inno Setup 6\iscc" ".\PacManII\PacManII.iss"
