/**\ingroup AdArcadeGame */
/*@{*/

/**	
 *	@file	
 *	File: addefinitions.hpp \n
 *	Framework: Commty Game Library (CGL) \n
 *	Author: Ignacio Cea Fornies (Community Networks) \n
 *	Creation Date: 25/03/2018 \n
 *	Description: Defines advanced arcade library definitions. \n
 *	Versions: 1.0 Initial
 */

#ifndef __QGAMES_ADDEFINITIONS__
#define __QGAMES_ADDEFINITIONS__

// The basic parameters of the game
#define __QGAMES_GAMENAMEPARAMETER__				"GAMENAME"
#define __QGAMES_DEFAULTGAMENAME__					"Commtynets Game"
#define __QGAMES_GAMEICONPARAMETER__				"GAMEICON"
#define __QGAMES_DEFAULTGAMEICON__					__QGAMES_COMMTYNETSGAMELOGO__
#define __QGAMES_GAMESCREENXPOSPARAMETER__			"SCREENXPOSITION"
#define __QGAMES_DEFAULTSCREENXPOSITION__			10
#define __QGAMES_GAMESCREENYPOSPARAMETER__			"SCREENYPOSITION"
#define __QGAMES_DEFAULTSCREENYPOSITION__			10
#define __QGAMES_GAMESCREENWIDTHPARAMETER__			"SCREENWIDTH"
#define __QGAMES_DEFAULTSCREENWIDTH__				640
#define __QGAMES_GAMESCREENHEIGHTPARAMETER__		"SCREENHEIGHT"
#define __QGAMES_DEFAULTSCREENHEIGHT__				480

// Some colors...
#define __QGAMES_WHITECOLOR__						QGAMES::Color (255, 255, 255, 255)
#define __QGAMES_GRAYCOLOR__						QGAMES::Color (100, 100, 100, 255)
#define __QGAMES_VERYGRAYCOLOR__					QGAMES::Color (200, 200, 200, 255)
#define __QGAMES_SHADOWCOLOR__						QGAMES::Color (100, 100, 100, 100)
#define __QGAMES_YELLOWCOLOR__						QGAMES::Color (255, 255, 51, 255)
#define __QGAMES_LIGHTYELLOWCOLOR__					QGAMES::Color (255, 255, 0, 255)
#define __QGAMES_DARKYELLOWCOLOR__					QGAMES::Color (255, 255, 102, 255)
#define __QGAMES_REDCOLOR__							QGAMES::Color (255, 51, 51, 255)
#define __QGAMES_TRANSPARENTREDCOLOR__				QGAMES::Color (255, 51, 51, 100)
#define __QGAMES_LIGHTREDCOLOR__					QGAMES::Color (255, 0, 0, 255)
#define __QGAMES_DARKREDCOLOR__						QGAMES::Color (204, 0, 0, 255)
#define __QGAMES_GREENCOLOR__						QGAMES::Color (0, 255, 0, 255)
#define __QGAMES_TRANSPARENTGREENCOLOR__			QGAMES::Color (0, 255, 0, 100)
#define __QGAMES_LIGHTGREENCOLOR__					QGAMES::Color (80, 255, 0, 255)
#define __QGAMES_DARKGREENCOLOR__					QGAMES::Color (48, 162, 48, 255)
#define __QGAMES_BLACKCOLOR__						QGAMES::Color (0, 0, 0, 255)
#define __QGAMES_TRANSPARENTBLACKCOLOR__			QGAMES::Color (0, 0, 0, 100)
#define __QGAMES_TRANSPARENTCOLOR__					QGAMES::Color (0, 0, 0, 0)
#define __QGAMES_BLUECOLOR__						QGAMES::Color (0, 0, 255, 255)
#define __QGAMES_TRANSPARENTBLUECOLOR__				QGAMES::Color (0, 0, 255, 100)
#define __QGAMES_LIGHTBLUECOLOR__					QGAMES::Color (51, 153, 255, 255)
#define __QGAMES_DARKBLUECOLOR__					QGAMES::Color (0, 0, 153, 255)
#define __QGAMES_ORANGECOLOR__						QGAMES::Color (255, 128, 0, 255)
#define __QGAMES_LIGHTORANGECOLOR__					QGAMES::Color (255, 153, 51, 255)
#define __QGAMES_DARKORANGECOLOR__					QGAMES::Color (204, 102, 0, 255)

// The default keys to control
#define __QGAMES_KEYLEFT__							0
#define __QGAMES_KEYRIGHT__							1
#define __QGAMES_KEYUP__							2
#define __QGAMES_KEYDOWN__							3
#define __QGAMES_KEYFIRE__							4
#define __QGAMES_KEYPAUSE__							5
#define __QGAMES_KEYSAVE__							6

// The graphics
// The logos
#define __QGAMES_COMMTYNETSGAMELOGO__				10000
#define __QGAMES_COMMTYNETSSMALLLOGO__				10001
#define __QGAMES_COMMTYNETSBIGLOGO__				10002
#define __QGAMES_COMMTYNETSPAUSELOGO__				10003
// The graphics used in the environmental conditions.
#define __QGAMES_DROPINRAINFORM__					10010
#define __QGAMES_WINDTRACEFORM__					10011
#define __QGAMES_RAINBOWFORM__						10012
#define __QGAMES_CLOUDS1FORM__						10013
#define __QGAMES_CLOUDS2FORM__						10014
#define __QGAMES_CLOUDS3FORM__						10015
#define __QGAMES_BUBBLES1FORM__						10016
#define __QGAMES_BUBBLES2FORM__						10017
// The graphics used to represents standard score objects.
#define __QGAMES_BLUEENERGYBARFORM__				10020
#define __QGAMES_REDENERGYBARFORM__					10021
#define __QGAMES_GREENENERGYBARFORM__				10022
#define __QGAMES_YELLOWENERGYBARFORM__				10023
#define __QGAMES_REDBALLFORM__						10024
#define __QGAMES_GREENBALLFORM__					10025

// The letters
// Type Courier
#define __QGAMES_COURIERLETTERS__					10000
// Courier 10
#define __QGAMES_COURIER10BLACKLETTERS__			20000
#define __QGAMES_COURIER10WHITELETTERS__			20001
// Type Ravie
#define __QGAMES_RAVIELETTERS__						10001
// Ravie 12
#define __QGAMES_RAVIE12BLUELETTERS__				20010
#define __QGAMES_RAVIE12GREENLETTERS__				20011
#define __QGAMES_RAVIE12ORANGELETTERS__				20012
// Ravie 24
#define __QGAMES_RAVIE24BLUELETTERS__				20020
#define __QGAMES_RAVIE24GREENLETTERS__				20021
#define __QGAMES_RAVIE24ORANGELETTERS__				20022
// Ravie 36
#define __QGAMES_RAVIE36BLUELETTERS__				20030
#define __QGAMES_RAVIE36GREENLETTERS__				20031
#define __QGAMES_RAVIE36ORANGELETTERS__				20032
// Ravie 72
#define __QGAMES_RAVIE72BLUELETTERS__				20040
#define __QGAMES_RAVIE72GREENLETTERS__				20041
#define __QGAMES_RAVIE72ORANGELETTERS__				20042
// Type ShowCard Gothic
#define __QGAMES_SCARDGOTHICLETTERS__				10002
// ShowCard Gothic 24
#define __QGAMES_SCARDGOTHIC24BLUELETTERS__			20100
#define __QGAMES_SCARDGOTHIC24BROWNLETTERS__		20101
#define __QGAMES_SCARDGOTHIC24GREENLETTERS__		20102
#define __QGAMES_SCARDGOTHIC24REDLETTERS__			20103
#define __QGAMES_SCARDGOTHIC24YELLOWLETTERS__		20104
// ShowCard Gothic 32
#define __QGAMES_SCARDGOTHIC32BLUELETTERS__			20110
#define __QGAMES_SCARDGOTHIC32BROWNLETTERS__		20111
#define __QGAMES_SCARDGOTHIC32GREENLETTERS__		20112
#define __QGAMES_SCARDGOTHIC32REDLETTERS__			20113
#define __QGAMES_SCARDGOTHIC32YELLOWLETTERS__		20114
// ShowCard Gothic 36
#define __QGAMES_SCARDGOTHIC36BLUELETTERS__			20120
#define __QGAMES_SCARDGOTHIC36BROWNLETTERS__		20121
#define __QGAMES_SCARDGOTHIC36GREENLETTERS__		20122
#define __QGAMES_SCARDGOTHIC36REDLETTERS__			20123
#define __QGAMES_SCARDGOTHIC36YELLOWLETTERS__		20124
// ShowCard Gothic 64
#define __QGAMES_SCARDGOTHIC64BLUELETTERS__			20130
#define __QGAMES_SCARDGOTHIC64BROWNLETTERS__		20131
#define __QGAMES_SCARDGOTHIC64GREENLETTERS__		20132
#define __QGAMES_SCARDGOTHIC64REDLETTERS__			20133
#define __QGAMES_SCARDGOTHIC64YELLOWLETTERS__		20134
// ShowCard Gothic 72
#define __QGAMES_SCARDGOTHIC72BLUELETTERS__			20140
#define __QGAMES_SCARDGOTHIC72BROWNLETTERS__		20141
#define __QGAMES_SCARDGOTHIC72GREENLETTERS__		20142
#define __QGAMES_SCARDGOTHIC72REDLETTERS__			20143
#define __QGAMES_SCARDGOTHIC72YELLOWLETTERS__		20144

// The basic sounds included in the library.
// WAV version
#define __QGAMES_JUMPWAVSOUND__						10000
#define __QGAMES_EATWAVSOUND__						10001
#define __QGAMES_CATCHWAVSOUND__					10002
#define __QGAMES_THROWWAVSOUND__					10003
#define __QGAMES_RAINWAVSOUND__						10004
#define __QGAMES_EARTHQUAKEWAVSOUND__				10005
#define __QGAMES_WINDWAVSOUND__						10006
#define __QGAMES_THUNDERWAVSOUND__					10007
#define __QGAMES_HURTWAVSOUND__						10008
#define __QGAMES_WICKWAVSOUND__						10009
#define __QGAMES_EXPLOSIONWAVSOUND__				10010
#define __QGAMES_BEEPWAVSOUND__						10011
#define __QGAMES_SAVEWAVSOUND__						10012
// MP3 version
#define __QGAMES_JUMPMP3SOUND__						20000
#define __QGAMES_EATMP3SOUND__						20001
#define __QGAMES_CATCHMP3SOUND__					20002
#define __QGAMES_THROWMP3SOUND__					20003
#define __QGAMES_RAINMP3SOUND__						20004
#define __QGAMES_EARTHQUAKEMP3SOUND__				20005
#define __QGAMES_WINDMP3SOUND__						20006
#define __QGAMES_THUNDERMP3SOUND__					20007
#define __QGAMES_HURTMP3SOUND__						20008
#define __QGAMES_WICKMP3SOUND__						20009
#define __QGAMES_EXPLOSIONMP3SOUND__				20010
#define __QGAMES_BEEPMP3SOUND__						20011
#define __QGAMES_SAVEMP3SOUND__						20012
// Channels
// Standard channel as background
#define __QGAMES_BACKGROUNDSOUNDCHANNEL__			0
// Standard channel for Weather sounds
#define __QGAMES_WHEATHERSOUNDCHANNEL__				1
// Standard channel for sounds related with characters
#define __QGAMES_ARTISTSOUNDCHANNEL__				2
// Standard channel for sounds related with th main characteres
#define __QGAMES_MAINCHARACTERSOUNDCHANNEL__		3
// A standard channel for sound related with the state of the game
#define __QGAMES_GAMESTATESOUNDCHANNEL__			4
// A standard channel for sound related witho general game situations
#define __QGAMES_GAMESOUNDCHANNEL__					5

// Wheather
// Weather conditions
#define __QGAMES_THUNDERWHEATHER__					10000
#define __QGAMES_THUNDERWHEATHERATTRSOUNDCHN__		"ThunderSoundChannel"
#define __QGAMES_THUNDERWHEATHERATTRSOUND__			"ThunderSoundId"
#define __QGAMES_THUNDERSWHEATHER__					10001
#define __QGAMES_THUNDERSWHEATHERATTRPROB__			"ThundersProbability"
#define __QGAMES_THUNDERSWHEATHERATTRFREQ__			"ThundersFrecuency"
#define __QGAMES_THUNDERSWHEATHERATTRSOUNDCHN__		"ThundersSoundChannel"
#define __QGAMES_THUNDERSWHEATHERATTRSOUND__		"ThundersSoundId"
#define __QGAMES_RAINWHEATHER__						10002
#define __QGAMES_RAINWHEATHERATTRDENSITY__			"RainDensity"
#define __QGAMES_RAINWHEATHERATTRSPEED__			"RainSpeed"
#define __QGAMES_RAINWHEATHERATTRSOUNDCHN__			"RainSoundChannel"
#define __QGAMES_RAINWHEATHERATTRSOUND__			"RainSoundId"
#define __QGAMES_RAINWHEATHERATTRBK__				"RainBackgroundId"
#define __QGAMES_RAINWHEATHERATTRDROP__				"RainDropId"
#define __QGAMES_EARTHQUAKEWHEATHER__				10003
#define __QGAMES_EARTHQUAKEWHEATHERATTRINTEN__		"EarthquakeIntensity"
#define __QGAMES_EARTHQUAKEWHEATHERATTRSDCHN__		"EarthQuakeSoundChannel"
#define __QGAMES_EARTHQUAKEWHEATHERATTRSOUND__		"EarthSoundId"
#define __QGAMES_WINDWHEATHER__						10004
#define __QGAMES_WINDWHEATHERATTRDENSITY__			"WindDensity"
#define __QGAMES_WINDWHEATHERATTRSPEED__			"WindSpeed"
#define __QGAMES_WINDWHEATHERATTRSOUNDCHN__			"WindSoundChannel"
#define __QGAMES_WINDWHEATHERATTRSOUND__			"WindSoundId"
#define __QGAMES_WINDWHEATHERATTRTRACE__			"WindTraceId"
#define __QGAMES_LIGHTNINGWHEATHER__				10005
#define __QGAMES_LIGHTNINGWHEATHERATTRSDCHN__		"LightningSoundChannel"
#define __QGAMES_LIGHTNINGWHEATHERATTRSOUND__		"LightningSoundId"
#define __QGAMES_LIGHTNINGSWHEATHER__				10006
#define __QGAMES_LIGHTNINGSWHEATHERATTRPROB__		"LightningsProbability"
#define __QGAMES_LIGHTNINGSWHEATHERATTRFREQ__		"LightningsFrecuency"
#define __QGAMES_LIGHTNINGSWHEATHERATTRSDCHN__		"LightningsSoundChannel"
#define __QGAMES_LIGHTNINGSWHEATHERATTRSOUND__		"LightningsSoundId"
#define __QGAMES_RAINBOWWHEATHER__					10007
#define __QGAMES_RAINBOWWHEATHERATTRSECONDS__		"SecondsRainbow"
#define __QGAMES_RAINBOWWHEATHERDEFATTRSECS__		3.0
#define __QGAMES_RAINBOWWHEATHERATTRFORM__			"RainbowFormId"
#define __QGAMES_STORMWHEATHER__					10008
#define __QGAMES_CLOUDSWHEATHER__					10009
#define __QGAMES_CLOUDSWHEATHERATTRDENSITY__		"CloudsDensity"
#define __QGAMES_CLOUDSWHEATHERATTRSPEED__			"CloudsSpeed"
#define __QGAMES_CLOUDSWHEATHERATTRSOUNDCHN__		"CloudsSoundChannel"
#define __QGAMES_CLOUDSWHEATHERATTRSOUND__			"CloudsSoundId"
#define __QGAMES_CLOUDSWHEATHERATTRCLOUDS__			"CloudsIds"

// The events related with that whether conditions
#define __QGAMES_THUNDERSTARTS__					10000
#define __QGAMES_THUNDERFINISHES__					10001
#define __QGAMES_RAINSTARTS__						10002
#define __QGAMES_RAINFINISHES__						10003
#define __QGAMES_EARTHQUAKESTARTS__					10004
#define __QGAMES_EARTHQUAKEFINISHES__				10005
#define __QGAMES_WINDSTARTS__						10006
#define __QGAMES_WINDFINISHES__						10007
#define __QGAMES_LIGHTNINGSTARTS__					10008
#define __QGAMES_LIGHTNINGFINISHES__				10009
#define __QGAMES_RAINBOWSTARTS__					10010
#define __QGAMES_RAINBOWFINISHES__					10011
#define __QGAMES_CLOUDSSTARTS__						10012
#define __QGAMES_CLOUDSFINISHES__					10013

// The movements
// The maximum acceleration and speed in pixels / sg2 y pixels / sg respectively by default in a movement
#define __QGAMES_MOVMAXIMUMACCELERATION__			0
#define __QGAMES_MOVMAXIMUMSPEED__					QGAMES::Game::game () -> mainScreen () -> visualWidth () / 10 // 10 sg crossing the screen...
// Events related with movements */
#define __QGAMES_MOVEMENTLIMITREACHED__				10023
#define __QGAMES_MOVEMENTSPEEDLIMITREACHED__		10024
#define __QGAMES_NOTBOUNCINGMOVEMENTANYMORE__		10025
#define __QGAMES_BOUNCINGMOVEMENT__					10026
#define __QGAMES_MOVEMENTSTARTSBACK__				10027
// The standard movement. When nothing moves
#define __QGAMES_MOVNOMOVEMENTID__					10000
// Type of curves for the default curve builder...
#define __QGAMES_NOMOVEMENTTRACE__					0 // Stay
#define __QGAMES_LINEARCURVEMOVEMENTTRACE___		1 // A line
#define __QGAMES_CIRCULARCURVEMOVEMENTTRACE___		2 // A circle or a part of it (clockwise or anticlockwise regardinf the initial and final angles)
#define __QGAMES_SINUSOIDALCURVEMOVEMENTTRACE__		3 // A sinusoide (clockwise or anticlokwise)
#define __QGAMES_COMPLEXCURVEMOVEMENTTRACE__		1000 // A complex combination of them...
#define __QGAMES_LINEARDANCINGCURVEMOVTRACE___		4 // Go and back by a line
#define __QGAMES_CIRCULARDANCINGCURVEMOVTRACE___	5 // Go and back in a circle 
#define __QGAMES_XYCIRCLEANDLINERIGHTMOVTRACE__		6 // A circle (or part of it) anticlockwise and then a line
#define __QGAMES_XYCIRCLEANDLINELEFTMOVTRACE__		7 // A circle (or part of it) clockwise and then a line
#define __QGAMES_XYLINECIRCLELINEMOVTRACE__			8 // A line, then a circle (or part of it) and then again a line	

// The game states
// The different standard game states
#define __QGAMES_GAMESTATENULLTYPE__				10025
#define __QGAMES_GAMESTATEWAITINGTIMETYPE__			10000
#define __QGAMES_GAMESTATEWAITINGTIMEATTRTIME__		"TIME"
#define __QGAMES_GAMESTATEUNTILENTERTYPE__			10001
#define __QGAMES_GAMESTATEWAITORUNTILKEYTYPE__		10002
#define __QGAMES_GAMESTATESHOWSTDTEXTTYPE__			10003
#define __QGAMES_GAMESTATESHOWSTDTXTATTRTEXT__		"TEXT"
#define __QGAMES_GAMESTATESHOWSTDTXTATTRFONT__		"FONT"
#define __QGAMES_GAMESTATESHOWPLAYERNUMTYPE__		10004
#define __QGAMES_GAMESTATEFPSTYPE__					10005 // The generic
#define __QGAMES_GAMESTATESPENDUNLESSKEYTYPE__		10006
#define __QGAMES_GAMESTATEFPS__						10005
#define __QGAMES_GAMESTATEFPSNAME__					"10005"
#define __QGAMES_GAMESTATEBLINKINGTEXTTYPE__		10007
#define __QGAMES_GAMESTATEBLINKINGTEXTNAME__		"10007"
#define __QGAMES_GAMESTATEPLAYSOUNDTYPE__			10010
#define __QGAMES_GAMESTATEPLAYSOUND__				10010
#define __QGAMES_GAMESTATEPLAYSOUNDNAME__			"10010"
#define __QGAMES_GAMESTATESHOWFIXFORMTYPE__			10020
#define __QGAMES_GAMESTATESHOWFIXFORM__				10020
#define __QGAMES_GAMESTATESHOWFIXFORMNAME__			"10020"
#define __QGAMES_GAMESTATESHOWFORMTYPE__			10030
#define __QGAMES_GAMESTATESHOWFORM__				10030
#define __QGAMES_GAMESTATESHOWFORMNAME__			"10030"
#define __QGAMES_GAMESTATESHOWENTITYTYPE__			10040
#define __QGAMES_GAMESTATESHOWENTITY__				10040
#define __QGAMES_GAMESTATESHOWENTITYNAME__			"10040"
#define __QGAMES_GAMESTATELOADINGTYPE__				10050
#define __QGAMES_GAMESTATELOADING__					10050
#define __QGAMES_GAMESTATELOADINGNAME__				"10050"
#define __QGAMES_GAMESTATECOUNTINGDOWNTYPE__		10060
#define __QGAMES_GAMESTATECOUNTINGDOWN__			10060
#define __QGAMES_GAMESTATECOUNTINGDOWNNAME__		"10060"
#define __QGAMES_GAMESTATECOUNTDOWNSTDFRAMES__		9
#define __QGAMES_GAMESTATECOUNTDOWNSTDBSCFORM__		30000
#define __QGAMES_GAMESTATECOUNTDOWNSTDNUMBERS__		3
#define __QGAMES_GAMESTATEHALLOFFAMETYPE__  		10070
#define __QGAMES_GAMESTATEHALLOFFAME__  			10070
#define __QGAMES_GAMESTATEHALLOFFAMENAME__			"10070"
#define __QGAMES_GAMESTATEROLLINGFRMSTYPE__			10080
#define __QGAMES_GAMESTATEROLLINGFRMS__				10080
#define __QGAMES_GAMESTATEROLLINGFRMSNAME__			"10080"
#define __QGAMES_GAMESTATECREDITTITLESTYPE__		10090
#define __QGAMES_GAMESTATECREDITTITLES__			10090
#define __QGAMES_GAMESTATECREDITTITLESNAME__		"10090"
#define __QGAMES_GAMESTATECREDITTITLESTBLK__		"Titles"
#define __QGAMES_GAMESTATECREDITTITLEPARAM__		"Title"
#define __QGAMES_GAMESTATECREDITTITLEVALUEPRM__		"value"
#define __QGAMES_GAMESTATESHOWINSTTYPE__			10091
#define __QGAMES_GAMESTATESHOWINSTNAME__			"10091"
#define __QGAMES_GAMESTATESHOWINSTBLK__				"Instructions"
#define __QGAMES_GAMESTATESHOWINSTPARAM__			"Instruction"
#define __QGAMES_GAMESTATESHOWINSTLINEPRM__			"line"
#define __QGAMES_GAMESTATESHOWINSTTYPEPRM__			"type"
#define __QGAMES_GAMESTATESHOWINSTFONTPRM__			"font"
#define __QGAMES_GAMESTATESHOWINSTPOSPRM__			"position"
#define __QGAMES_GAMESTATESHOWINSTREFPRM__			"reference"
#define __QGAMES_GAMESTATESELECTOPTIONSTYPE__		10100
#define __QGAMES_GAMESTATESELECTOPTIONS__			10100
#define __QGAMES_GAMESTATESELECTOPTIONSNAME__		"10100"
#define __QGAMES_GAMESTATEADVANCEDCTRLTYPE__		10101
#define __QGAMES_GAMESTATEADVANCEDCTRLPAUSE__		"PAUSEGAMESTATE"
#define __QGAMES_GAMESTATEADVANCEDCTRL__			10101
#define __QGAMES_GAMESTATEADVANCEDCTRLNAME__		"10101"
#define __QGAMES_GAMESTATEROLLSTATESTYPE__			10102
#define __QGAMES_GAMESTATEROLLSEPSBLOCK__			"Separations"
#define __QGAMES_GAMESTATEROLLSEPBLOCK__			"Separation"
// The events related with the rolling game state
#define __QGAMES_SEPARATION0PERCENTAGE__			10030
#define __QGAMES_SEPARATION100PERCENTAGE__			10031
#define __QGAMES_ROLLINGGAMESTATESFINISHED__		10032
// The main attributes of the game states' properties...
#define __QGAMES_GAMESTATEPROPATTRFADE__			"FADE"
#define __QGAMES_GAMESTATEPROPATTRELAPSEDCYCLES__	"ELAPSEDCYCLES"
#define __QGAMES_GAMESTATEPROPATTRNFADECHANGES__	"NUMBERFADECHANGES"
#define __QGAMES_GAMESTATEPROPATTRFADESTEP__		"FADESTEP"
#define __QGAMES_GAMESTATEPROPATTRPOSREF__			"POSREFERENCE"
#define __QGAMES_GAMESTATEPROPATTRPOSITION__		"POSITION"
#define __QGAMES_GAMESTATEPROPATTRORIENTATION__		"ORIENTATION"
#define __QGAMES_GAMESTATEPROPATTRSOUND__			"SOUNDID"
#define __QGAMES_GAMESTATEPROPATTRCHANNEL__			"CHANNELID"
#define __QGAMES_GAMESTATEPROPATTRFORM__			"FORMID"
#define __QGAMES_GAMESATTEPROPATTRUP__				"UP"
#define __QGAMES_GAMESTATEPROPATTRINITIALFADE__		"INITIALFADE"
#define __QGAMES_GAMESTATEPROPATTRFINALFADE__		"FINALFADE"
#define __QGAMES_GAMESTATEPROPATTRFADEINC__			"FADEINCREMENT"
#define __QGAMES_GAMESTATEPROPATTRLOOPSFADE__		"LOOPSPERFADECHANGE"
#define __QGAMES_GAMESTATEPROPATTRENTITY__			"ENTITYID"
#define __QGAMES_GAMESTATEPROPATTRCTRLPOS__			"CONTROLPOSITION"
#define __QGAMES_GAMESTATEPROPATTRREVERSE__			"REVERSE"
#define __QGAMES_GAMESTATEPROPATTRHORIZONTAL__		"HORIZONTAL"
#define __QGAMES_GAMESTATEPROPATTRBEEPSOUND__		"BEEPSOUNDID"
#define __QGAMES_GAMESTATEPROPATTRFRAMESPN__		"FRAMESPERNUMBER"
#define __QGAMES_GAMESTATEPROPATTRFRAMESOVP__		"FRAMESOVERLAPPED"
#define __QGAMES_GAMESTATEPROPATTRNUMBERS__			"NUMBERS"
#define __QGAMES_GAMESTATEPROPATTRFORMSLST__		"FORMS"
#define __QGAMES_GAMESTATEPROPATTRDELAY__			"DELAY"
#define __QGAMES_GAMESTATEPROPATTRSECONSCR__		"SECONDSONSCREEN"
#define __QGAMES_GAMESTATEPROPATTRDIRECTION__		"DIRECTION"
#define __QGAMES_GAMESTATEPROPATTRINSTANCES__		"INSTANCES"
#define __QGAMES_GAMESTATEPROPATTRSEQUENTIAL__		"SEQUENTIAL"
#define __QGAMES_GAMESTATEPROPATTRLPERTITLE__		"MAXLETTERSPERTITLE"
#define __QGAMES_GAMESTATEPROPATTRSEPARATION__		"SEPARATION"
#define __QGAMES_GAMESTATEPROPATTRTFONT__			"FONT"
#define __QGAMES_GAMESTATEPROPATTRTYPEROLL__		"TYPEROLLING"
#define __QGAMES_GAMESTATEPROPATTRTSTATENAME__		"STATENAME"
#define __QGAMES_GAMESTATEPROPATTRTTICKS__			"TICKS"
#define __QGAMES_GAMESTATEPROPATTRINCREMENT__		"INCREMENT"
#define __QGAMES_GAMESTATEPROPATTRSEPARATION__		"SEPARATION"
#define __QGAMES_GAMESTATEPROPATTRVISIBLEZONE__		"VISIBLEZONE"
#define __QGAMES_GAMESTATEPROPATTRMOVEMENT__		"MOVEMENT"
#define __QGAMES_GAMESTATEPROPATTRTOMOVE__			"TOMOVE"

// The GUI System
// The Standard GUI System
#define __QGAMES_STDGUISYSTEMID__					10000
#define __QGAMES_STDGUISYSTEMMAINWIDGET__			10001
#define __QGAMES_STDGUISYSTEMSTARTGAMEWDT__			10002
#define __QGAMES_STDGUISYSTEMLOADCONFWDT__			10003
#define __QGAMES_STDGUISYSTEMNUMBERPLYWDT__			10004
#define __QGAMES_STDGUISYSTEMTYPECTRLWDT__			10005
#define __QGAMES_STDGUISYSTEMCONFKEYSWDT__			10006
#define __QGAMES_STDGUISYSTEMLEVELDIFFWDT__			10007
#define __QGAMES_STDGUISYSTEMMUSICONWDT__			10008
#define __QGAMES_STDGUISYSTEMHALLOFFAMEWDT__		10009
#define __QGAMES_STDGUISYSTEMEXITWDT__				10010
#define __QGAMES_STDGUISYSTEMCONFKEYSID__			10100
#define __QGAMES_STDGUISYSTEMMAINCONFWIDGET__		10101
#define __QGAMES_STDGUISYSTEMCONFKEYUPWDT__			10102
#define __QGAMES_STDGUISYSTEMCONFKEYDOWNWDT__		10103
#define __QGAMES_STDGUISYSTEMCONFKEYLEFTWDT__		10104
#define __QGAMES_STDGUISYSTEMCONFKEYRIGHTWDT__		10105
#define __QGAMES_STDGUISYSTEMCONFKEYFIGHTWDT__		10106
#define __QGAMES_STDGUISYSTEMCONFKEYPAUSEWDT__		10107
#define __QGAMES_STDGUISYSTEMCONFKEYSAVEWDT__		10108
#define __QGAMES_STDGUISYSTEMCONFKEYBACKWDT__		10109

// The entities
// The entity used when the game is paused.
#define __QGAMES_COMMTYNETSPAUSEENTITYID__			10000
#define __QGAMES_COMMTYNETSPAUSEENTITYATION__		0 // The basic animation
#define __QGAMES_COMMTYNETSPAUSEENTITYSTATE__		0 // The basic state (considers the movement no movement)

// The layers
// Attributes for the visual effects...
// The visual effect related with a form changing in the layer.
#define __QGAMES_VEFFECTFORMSATTRFORM__				"FORM"
#define __QGAMES_VEFFECTFORMSATTRNUMASPECTS__		"ASPECTS"
#define __QGAMES_VEFFECTFORMATTRSQAURE__			"ZONE"
// Attributes to define the movement of a platform
// There are a couple of default movements
#define __QGAMES_LAYERTYPOFMOVEMENT__				"TYPEMOV"
#define __QGAMES_LAYERTYPEOFMOVSTRAIGHT__			0 // Like a line
#define __QGAMES_LAYERTYPEOFMOVCIRCULAR__			1 // Like a circle
#define __QGAMES_LAYERTYPEOFMOVBSTRAIGHT__			2 // Going back and forth in a line
#define __QGAMES_LAYERTYPEOFMOVBCIRCULAR__			3 // Going back and forth in a circle
#define __QGAMES_LAYERTYPEOFMOVCCIRCULAR__			4 // A circle cycle
#define __QGAMES_LAYERTYPEOFMOVSTRAIGHTCICLIC__		5 // A ciclic straight movement
// Attributes related with the movements
#define __QGAMES_LAYERMOVNUMBERCYCLES__				"CYCLES"
#define __QGAMES_LAYERMOVDEFAULTNUMBERCYCLES__		-1 // Ethernal if any...
#define __QGAMES_LAYERMOVEMENTSPEED__				"SPEED"
#define __QGAMES_LAYERMOVEMENTDEFAULTSPEED__		1
// Just with the circular ones...
#define __QGAMES_LAYERCIRCULARMOVRADIX__			"RADIX"
#define __QGAMES_LAYERCIRCULARMOVDEFAULTRADIX__		100
#define __QGAMES_LAYERCIRCULARMOVINITANGLE__		"INITANGLE"
#define __QGAMES_LAYERCIRCULARMOVDEFINITANGLE__		__BD 0
#define __QGAMES_LAYERCIRCULTARMOVFINALANGLE__		"FINALANGLE"
#define __QGAMES_LAYERCIRCULARMOVANGLESTEP__		"ANGLE"
#define __QGAMES_LAYERCIRCULARMOVDEFANGLESTEP__		__BD (__PI / 18)
#define __QGAMES_LAYERCIRCULATMOVCLOCKWISE__		"CLOCKWISE"
// With the linear ones
#define __QGAMES_LAYERSTRAIGHTMOVLENGTH__			"LENGTH"
#define __QGAMES_LAYERSTRAIGHTDEFMOVLENGTH__		100 // Pixels...
#define __QGAMES_LAYERSTRAIGHTMOVDIRECTION__		"DIRECTION"
#define __QGAMES_LAYERSTRAIGHTDEFMOVDIRECTION__		"1,0,0" // Following the positive X axis...
// Attributes related with the updater of a tile layer
// There are a couple of default movements
#define __QGAMES_LAYERTYPOFUPDATER__				"TYPEUPDATE"
#define __QGAMES_LAYERTYPEOFUPDWAVE__				0 // Like a wave
#define __QGAMES_LAYERTYPEOFUPDFLOW__				1 // Like a flow
// Attributes related with all updater
#define __QGAMES_LAYERUPDLOOPSTO__					"LOOPS"
#define __QGAMES_LAYERUPSDEFAULTLOOPSTO__			60 // The usual frame rate...
#define __QGAMES_LAYERUPDLISTOFTILES__				"TILES"
#define __QGAMES_LAYERUPDDEFAULTLISTOFTILES__		"" // None...
// Attributes related with the wave like updating
#define __QGAMES_LAYERWAVEUPDACCELERATION__			"ACCELERATION"
#define __QGAMES_LAYERWAVEUPDDEFACCELERATION__		0.5
#define __QGAMES_LAYERWAVEUPDSPEED__				"SPEED"
#define __QGAMES_LAYERWAVEUPDDEFAULTSPEED__			1.0
// Attributes related with the visual effect associated to a tile layer
// There are a couple of default visual effects
#define __QGAMES_LAYERTYPEOFVISUALEFFECT__			"VISUALEFFECT"
#define __QGAMES_LAYERRVISUALEFFECTFORMON__			0 // A form over every tile...
#define __QGAMES_LAYERVEFFECTFORMONSPEED__			"SPEEDCHANGE"
#define __QGAMES_LAYERVEFFECTFORMONDEFSPEED_		6
#define __QGAMES_LAYERVEFFECTFORMONPTOAPPEAR__		"PROBABILITYTOAPPEAR"
#define __QGAMES_LAYERVEFFECTFORMONDEFPTOAPPEAR__	__BD 0.6

// The configuration object
// Hall of hame
// Standard structure for the hall of fame.
#define __QGAMES_HALLOFFAMEATTRSCORE__				0 // The score
#define __QGAMES_HALLOFFAMEATTRKILLS__				1 // The number of enemies killed

// Background builder adds on
// To define the type of object builder map adds on to create a background map
#define __QGAMES_BACKGROUNDOBJECTMAP__				10000

// Runtime values structure
#define __QGAMES_RUNTIMEVALUESIMPULSESTYPE__		"IMPULSES"

#endif
  
// End of the file
/*@}*/