/** \ingroup PACMAN */
/*@{*/

/**	
 *	@file	
 *	File: pcdefs.hpp \n
 *	Framework: Commty Game Library (CGL) \n
 *	Author: Ignacio Cea Fornies (Community Networks) \n
 *	Creation Date: 21/08/2021 \n
 *	Description: Defines and general includes of PACMAN
 *	Versions: 1.0 Initial
 */

#ifndef __PACMANIIDEFINES__
#define __PACMANIIDEFINES__

#include <Room/rminclude.hpp>

// Configuration parameters
#define __PACMAN_MAXNUMBEROFLIVESPARAMETER__					"LIVES"
#define __PACMAN_DEFAULTMAXNUMBEROFLIVESPARAMETER__				"3"
#define __PACMAN_LEVELPARAMETER__								"LEVEL"
#define __PACMAN_DEFAULTLEVELPARAMETER__						"1"
#define __PACMAN_MAXNUMBERLEVELS__								100
#define __PACMAN_SHOWPFSPARAMETER__								"FPS"
#define __PACMAN_DEFAULTSHOWFPSPARAMETER__						"NO"
#define __PACMAN_DRAWARTISTTARGETPARAMETER__					"DRAWTARGET"
#define __PACMAN_DEFAULTDRAWARTISTTARGETPARAMETER__				"NO"
#define __PACMAN_PASSWORDPARAMETER__							"PASSWORD"
#define __PACMAN_DEFAULTPASSWORDPARAMETER__						"---"
#define __PACMAN_MAXNUMBEROFLIVESINSCREEN__						6
#define __PACMAN_MAXNUMBEROFFRUITSINSCREEN__					8

// Important forms
#define __PACMAN_PACMANLIVESFORM__								50000
#define __PACMAN_PACMANFRUITSFORM__								50022

// Maze info
// Important parameters at maze info
#define __PACMAN_MAZEINFOZONE__									4
#define __PACMAN_MAZEINFOTUNNELCONNECTION__						5
#define __PACMAN_MAZEINFODIRZONE__								6
// Definition of the different areas in the maze
#define __PACMAN_MAZENUMBERPOSSIBLEZONES__						10
#define __PACMAN_MAZETUNELLPATHZONE__							0
#define __PACMAN_MAZEMONSTERSHOMEZONE__							1
// These two areas are special. The rest will be zones with the movement reduced...
#define __PACMAN_MAZEHORIZONTALMOVEMENTZONES__					{ 2, 3, 4 }
#define __PACMAN_MAZEVERTICALMOVEMENTZONES__					{ 5, 6, 7 }

// Sounds
#define __PACMAN_SOUNDBEGINNING__								50000
#define __PACMAN_SOUNDCHOMP__									50001
#define __PACMAN_SOUNDDEATH__									50002
#define __PACMAN_SOUNDEATFRUIT__								50003
#define __PACMAN_SOUNDEATGHOST__								50004
#define __PACMAN_SOUNDEXTRAPAC__								50005
#define __PACMAN_SOUNDINTERMISSION__							50006
#define __PACMAN_SOUNDSIREN__									50007
#define __PACMAN_SOUNDSIRENFAST__								50008
#define __PACMAN_SOUNDSIRENVERYFAST__							50009
#define __PACMAN_SOUNDTHREATING__								50010

// Letters
#define __PACMAN_NEWTOURLETTERS__								60000
#define __PACMAN_NEWTOUR24BLUELETTERS__							60000
#define __PACMAN_NEWTOUR24GREENLETTERS__						60001
#define __PACMAN_NEWTOUR24REDLETTERS__							60002
#define __PACMAN_NEWTOUR24YELLOWLETTERS__						60003
#define __PACMAN_NEWTOUR36BLUELETTERS__							60010
#define __PACMAN_NEWTOUR36GREENLETTERS__						60011
#define __PACMAN_NEWTOUR36REDLETTERS__							60012
#define __PACMAN_NEWTOUR36YELLOWLETTERS__						60013
#define __PACMAN_NEWTOUR48BLUELETTERS__							60020
#define __PACMAN_NEWTOUR48GREENLETTERS__						60021
#define __PACMAN_NEWTOUR48REDLETTERS__							60022
#define __PACMAN_NEWTOUR48YELLOWLETTERS__						60023

// GUI Systems
// To ask for the name of the player
#define __PACMAN_PLAYERNAMEGUISYSTEM__							50000
#define __PACMAN_PLAYERNAMEOPTIONID__							50002
// GUI System used for the options when playing 
#define __PACMAN_OPTIONWHENPLAYINGGUISYSTEM__					50200
#define __PACMAN_OPTIONSGUISYSTEMMAINWIDGET__					50201
#define __PACMAN_GUISYSTEMSAVEGAMEWDT__							50202
#define __PACMAN_GUISYSTEMEXITGAMEWDT__							50203
#define __PACMAN_GUISYSTEMCONTINUEGAMEWDT__						50204

// Game states types
/** Name of the player playing */
#define __PACMAN_GAMESTATEPLAYERNAMETYPE__						50000
/** Name of the current level */
#define __PACMAN_GAMESTATELEVELTYPE__							50011
/** To create the Playing Game State Control */
#define __PACMAN_GAMESTATECONTROLPLAYINGTYPE__					50080
/** To create the Playing Game State (inside Playing Game State Control) */
#define __PACMAN_GAMESTATEPLAYINGTYPE__							50081
/** To create the Options when Playing Game State */
#define __PACMAN_GAESTATEOPTIONSWHENPLAYTYPE__					50082
/** Special version of the hall of the fame */
#define __PACMAN_GAMESTATEHALLOFFAMETYPE__						50070
/** Special version to control all the game */
#define __PACMAN_GAMESTATECTRLTYPE__							50101
/** To initialize the game, and to avoid doing so at init method in game class. */
#define __PACMAN_GAMESTATEINITIALIZEGAMETYPE__					50102
/** To show the battleship moving in the right side of the screen. */
#define __PACMAN_GAMESTATEMOVINGMONSTERSTYPE__					50103
#define __PACMAN_GAMESTATEMOVMONSTERATTRFADE__					"FADE"
#define __PACMAN_GAMESTATEMOVMONSTERATTRPOSITION__				"POSITION"
#define __PACMAN_GAMESTATEMOVMONSTERATTRITERATIONS__			"ITERATIONS"
#define __PACMAN_GAMESTATEMOVMONSTERATTRBIGPACMAN__				"BIGPACMAN"
/** To stop the game playing. */
#define __PACMAN_GAMESTATESTOPPINGELEMENTSTYPE__				50105
#define __PACMAN_GAMESTATESTOPPINGELEMENTSATTRSTOPALL__			"STOPALL"
#define __PACMAN_GAMESTATESTOPPINGELEMENTSATTRHIDEMONSTERS__	"HIDEMONSTERS"
#define __PACMAN_GAMESTATESTOPPINGELEMENTSATTRHIDETHINGS__		"HIDETHINGS"
#define __PACMAN_GAMESTATESTOPPINGELEMENTSATTRVPACMAN__			"VANISHPACMAN"
/** To blink the map. */
#define __PACMAN_GAMESTATEBLINKMAZEMAPTYPE__					50104
#define __PACMAN_GAMESTATEBLINKMAZEATTRBLINKTIME__				"BLINKINGTIME"
#define __PACMAN_GAMESTATEBLINKMAZEATTRNUMBERBLINKS__			"NUMBERBLINKS"

// Game States
#define __PACMAN_STANDARDCONTROLGAMESTATE__						50000
#define __PACMAN_BEFOREPLAYINGGAMESTATE__						50101
#define __PACMAN_SHOWINGTHELEVELGAMESTATE__						50102
#define __PACMAN_PLAYINGGAMESTATE__								50107
#define __PACMAN_OPTIONSWHENPLAYINGGAMESTATE__					50200
#define __PACMAN_PLAYERGAMEOVERGAMESTATE__						50022
#define __PACMAN_MENUGAMESTATE__								50009
#define __PACMAN_CONTROLPLAYINGGAMESTATE__						50100
#define __PACMAN_PLAYERDIEDGAMESTATE__							50019

// The entities of the game
// Score Objects
#define __PACMAN_LIVESSCOBJID__									60000
#define __PACMAN_GAMETIMECOUNTERID__							60001
#define __PACMAN_GAMESCOREID__									60002
#define __PACMAN_GAMESCOREFIXTEXTBASEID__						60003
#define __PACMAN_GAMESCOREFRUITSCARRIEDID__						60004
// Characters
#define __PACMAN_NUMBERENTITIES__								10
// Pacman
#define __PACMAN_PACMANBASEENTITYID__							50000
#define __PACMAN_PACMANSTATBETWENSTANDANDEATING__				8
#define __PACMAN_PACMANSTATESTANDLOOKINGRIGHT__					0
#define __PACMAN_PACMANSTATESTANDLOOKINGLEFT__					1
#define __PACMAN_PACMANSTATESTANDLOOKINGUP__					2
#define __PACMAN_PACMANSTATESTANDLOOKINGDOWN__					3
#define __PACMAN_PACMANSTATESTANDEATINGLOOKINGRIGHT__			4
#define __PACMAN_PACMANSTATESTANDEATINGLOOKINGLEFT__			5
#define __PACMAN_PACMANSTATESTANDEATINGLOOKINGUP__				6
#define __PACMAN_PACMANSTATESTANDEATINGLOOKINGDOWN__			7
#define __PACMAN_PACMANSTATEEATINGLOOKINGRIGHT__				8
#define __PACMAN_PACMANSTATEEATINGLOOKINGLEFT__					9
#define __PACMAN_PACMANSTATEEATINGLOOKINGUP__					10
#define __PACMAN_PACMANSTATEEATINGLOOKINGDOWN__					11
#define __PACMAN_BIGPACMANSTATEEATINGLOOKINGRIGHT__				12
#define __PACMAN_BIGPACMANSTATEEATINGLOOKINGLEFT__				13
#define __PACMAN_PACMANSTAYMOVEMENTBASEID__						570000
#define __PACMAN_PACMANEATINGMOVEMENTBASEID__					550000
// Monsters
#define __PACMAN_MONSTERSTATEMOVINGANDLOOKINGRIGHT__			0
#define __PACMAN_MONSTERSTATEMOVINGANDLOOKINGLEFT__				1
#define __PACMAN_MONSTERSTATEMOVINGANDLOOKINGUP__				2
#define __PACMAN_MONSTERSTATEMOVINGANDLOOKINGDOWN__				3
#define __PACMAN_MONSTERSTATERUNNINGAWAY__						4
#define __PACMAN_MONSTERSTATEEATEN__							5
#define __PACMAN_MONSTERSTATEATHOMELOOKINGRIGHT__				6
#define __PACMAN_MONSTERSTATEATHOMELOOKINGLEFT__				7
#define __PACMAN_MONSTERSTATEATHOMELOOKINGUP__					8
#define __PACMAN_MONSTERSTATEATHOMELOOKINGDOWN__				9
#define __PACMAN_MONSTERSTATERUNNINGAWAYBLINK__					10
// Inky
#define __PACMAN_INKYBASEENTITYID__								50010
#define __PACMAN_INKYMAZEMOVEMENTBASEID__						550010
#define __PACMAN_INKYATHOMEMOVEMENTBASEID__						580010
// Blinky
#define __PACMAN_BLINKYBASEENTITYID__							50020
#define __PACMAN_BLINKYMAZEMOVEMENTBASEID__						550020
#define __PACMAN_BLINKYATHOMEMOVEMENTBASEID__					580020
// Pinky
#define __PACMAN_PINKYBASEENTITYID__							50030
#define __PACMAN_PINKYMAZEMOVEMENTBASEID__						550030
#define __PACMAN_PINKYATHOMEMOVEMENTBASEID__					580030
// Clyde
#define __PACMAN_CLYDEBASEENTITYID__							50040
#define __PACMAN_CLYDEMAZEMOVEMENTBASEID__						550040
#define __PACMAN_CLYDEATHOMEMOVEMENTBASEID__					580040
// The fruits
#define __PACMAN_FRUITBASEENTITYID__							50050
#define __PACMAN_NUMBERTYPESFRUIT__								12
#define __PACMAN_FRUIT01STATESTAYING__							0
#define __PACMAN_FRUIT02STATESTAYING__							1
#define __PACMAN_FRUIT03STATESTAYING__							2
#define __PACMAN_FRUIT04STATESTAYING__							3
#define __PACMAN_FRUIT05STATESTAYING__							4
#define __PACMAN_FRUIT06STATESTAYING__							5
#define __PACMAN_FRUIT07STATESTAYING__							6
#define __PACMAN_FRUIT08STATESTAYING__							7
#define __PACMAN_FRUIT09STATESTAYING__							8
#define __PACMAN_FRUIT10STATESTAYING__							9
#define __PACMAN_FRUIT11STATESTAYING__							10
#define __PACMAN_FRUIT12STATESTAYING__							11
#define __PACMAN_FRUITSTAYINGMOVEMENTBASEID__					550050
#define __PACMAN_FRUIT01STATEMOVING__							20
#define __PACMAN_FRUIT02STATEMOVING__							21
#define __PACMAN_FRUIT03STATEMOVING__							22
#define __PACMAN_FRUIT04STATEMOVING__							23
#define __PACMAN_FRUIT05STATEMOVING__							24
#define __PACMAN_FRUIT06STATEMOVING__							25
#define __PACMAN_FRUIT07STATEMOVING__							26
#define __PACMAN_FRUIT08STATEMOVING__							27
#define __PACMAN_FRUIT09STATEMOVING__							28
#define __PACMAN_FRUIT10STATEMOVING__							29
#define __PACMAN_FRUIT11STATEMOVING__							30
#define __PACMAN_FRUIT12STATEMOVING__							31
#define __PACMAN_FRUITMAZEMOVEMENTBASEID__						580050

// The Sceneblocks and its properties
#define __PACMAN_MONSTERSCENEBLOCKBASEID__						10000
#define __PACMAN_MONSTERSCENEBLOCKNUMBER__						1000
#define __PACMAN_MONSTERSCENEBLOCKLOOKPOSITIONATTR__			"LOOKFORPOSITION"
#define __PACMAN_MONSTERSCENEBLOCKENTITYIDATTR__				"ENTITYID"
#define __PACMAN_MONSTERSCENEBLOCKNUMBEERMONSTERATTR__			"MONSTERNUMBER"
#define __PACMAN_MONSTERSCENEBLOCKPOINTSATTR__					"POINTS"
#define __PACMAN_MONSTERSCENEBLOCKXOFFSETATTR__					"XOFFSET"
#define __PACMAN_MONSTERSCENEBLOCKYOFFSETATTR__					"YOFFSET"
#define __PACMAN_THINGSCENEBLOCKENTITYIDATTR__					"ENTITYID"
#define __PACMAN_THINGSCENEBLOCKTYPEATTR__						"TYPE"
#define __PACMAN_THINGSCENEBLOCKPOINTSATTR__					"POINTS"
#define __PACMAN_THINGSCENEBLOCKSECONDSTOAPPEARATTR__			"SECONDSTOAPPEAR"
#define __PACMAN_THINGSCENEBLOCKSECONDSTODISAPPEARATTR__		"SECONDSTODISAPPEAR"
#define __PACMAN_THINGSCENEBLOCKSPEEDATTR__						"SPEED"
#define __PACMAN_THINGSCENEBLOCKPOSITIONIDATTR__				"POSITIONID"
#define __PACMAN_FRUITSCENEBLOCKBASEID__						11000
#define __PACMAN_FRUITSCENEBLOCKNUMBER__						1000

// Events
// Related with the score objects
#define __PACMAN_LIVESACTUALIZED__								60000
#define __PACMAN_LIVESVALUEPARAMETER__							0
#define __PACMAN_GAMETIMEACTUALIZED__							60001
#define __PACMAN_GAMETIMEVALUEPARAMETER__						0
#define __PACMAN_SCOREACTUALIZED__								60002
#define __PACMAN_SCOREVALUEPARAMETER__							0
#define __PACMAN_FRUITSCARRIEDACTUALIZED__						60003
#define __PACMAN_FRUITSCARRIEDVALUEPARAMETER__					0
#define __PACMAN_PACMANPOINTSHIGHLIGHTREACHED__					60004
// Related with the input handler...
#define __PACMAN_MOVINGUPEVENT__								50000
#define __PACMAN_MOVINGRIGHTEVENT__								50001
#define __PACMAN_MOVINGUPRIGHTEVENT__							50002
#define __PACMAN_MOVINGDOWNEVENT__								50003
#define __PACMAN_MOVINGDOWNRIGHTEVENT__							50004
#define __PACMAN_MOVINGLEFTEVENT__								50005
#define __PACMAN_MOVINGUPLEFTEVENT__							50006
#define __PACMAN_MOVINGDOWNLEFTEVENT__							50007
#define __PACMAN_NOMOVINGEVENT__								50008
#define __PACMAN_FIREEVENT__									50009
// Related with the situation of the pacman...
#define __PACMAN_PACMANDESTROYED__								50100
#define __PACMAN_PACMANREACHEDGOAL__							50101
#define __PACMAN_PACMANEATMONSTER__								50102
#define __PACMAN_PACMANEATFRUIT__								50103
// A ball has been eaten...
#define __PACMAN_BALLEATEN__									50200
// And the scene has been completed...
#define __PACMAN_SCENECOMPLETED__								50201
// Related with the movement in the maze
#define __PACMAN_LIMITMOVEMENTREACHED__							50202
#define __PACMAN_MOVEMENTDORIENTATIONCHANGED__					50203
// Related with the action blocks...
#define __PACMAN_MONSTERSTARTEDTOMOVE__							50204

// The World and Scenes used for the game
#define __PACMAN_BASICWORLD__									50000
// The Scenes
#define __PACMAN_BASICBLOCKSCENES__								50000
// The Maps
#define __PACMAN_BASICMAPNUMBERCOLORS__							4
#define __PACMAN_BASICBLUEMAP__									50000
#define __PACMAN_BASICGREENMAP__								50100
#define __PACMAN_BASICYELLOWMAP__								50200
#define __PACMAN_BASICREDMAP__									50300
// The Scenes used for testing...
// The Scenes defined just por testing purposes
#define __PACMAN_TESTINGBLOCKSCENES__							50100
// The Maps used for testing...
#define __PACMAN_TESTINGMAP__									52000

// Name of the standard layers every defined map has to content minimum
#define __PACMAN_BACKGROUNDLAYERNAME__							"Background"
#define __PACMAN_ARTISTSLOCATIONSLAYERNAME__					"ArtistsLocations"
#define __PACMAN_MAZELOCATIONSLAYERNAME__						"MazeLocations"
#define __PACMAN_MAZEZONESLAYERNAME__							"MazeZones"
#define __PACMAN_DIRECTIONSLAYERNAME__							"Directions"
#define __PACMAN_MAZELAYERNAME__								"Maze"
// Name of the different forms containing the tiles used to draw
#define __PACMAN_FORMTILESMAZENAME__							"corners"
// The types of tiles in pacman: either a limit, a normal ball or power...
#define __PACMAN_LIMITTILE__									50000
#define __PACMAN_PATH__											50001

// Buouy to stop the movement of the character
#define __PACMAN_TOSTOPBUOYID__									0
#define __PACMAN_TOCHASEBUOYID__								1

#endif
  
// End of the file
/*@}*/