/** \ingroup Game */
/*@{*/

/**	
 *	@file	
 *	File: definitions.hpp \n
 *	Framework: Commty Game Library (CGL) \n
 *	Author: Ignacio Cea Fornies (Community Networks) \n
 *	Creation Date: 01/12/2014 \n
 *	Description: Defines common definitions for the game library. \n
 *	Versions: 1.0 Initial
 */

#ifndef __QGAMES_DEFINITIONS__
#define __QGAMES_DEFINITIONS__

#include <string>
#include <limits>
#include <assert.h>

namespace QGAMES
{
	typedef float bdata;
	typedef bdata bdata4[4];
	typedef bdata4 bdata44[4];
	#define bdata0 (bdata)0
	#define bdata1 (bdata)0.01
}

#define __QGAMES_LIBRARYVERSION__				"2.0.10"

#ifdef _WIN32
#define __OLDPATHWINDOWS_SEPARATOR__			"\\"
#endif
#define __PATH_SEPARATOR__						"/"

#define __PI									(QGAMES::bdata)3.1415926535897932384626433832795

#define __GAME_CONFIGURATIONFILE__				"conf.xml"
#define __GAME_PROPERTYATTRID__					"id"
#define __GAME_PROPERTYATTRVALUE__				"value"
#define __GAME_DATADIRPROPERTYNAME__			"DATADIR"
#define __GAME_DEFAULTDATADIR__					"./Temp"
#define __GAME_XSCALE__							"XSCALE"
#define __GAME_DEFAULTXSCALE__					"1"
#define __GAME_YSCALE__							"YSCALE"
#define __GAME_DEFAULTYSCALE__					"1"
#define __GAME_LOGTYPEPROPERTYNAME__			"LOG"
#define __GAME_DEFAULTLOGTYPE__					__QGAMES_COMMSCHANNELCONSOLELOG__

#define __GAME_PROPERTYGAMESTATESFILE__			"GAMESTATESFILE"
#define __GAME_GAMESTATESDEFINITIONSTDFILE__	"gamestates.xml"
#define __GAME_PROPERTYFORMSFILE__				"FORMSFILE"
#define __GAME_FORMSDEFINITIONSTDFILE__			"forms.xml" // ...in the same directory than the executed file...
#define __GAME_PROPERTYMASKFILE__				"MASKFILE"
#define __GAME_MASKDEFINITIONSSTDFILE__			"masks.xml"
#define __GAME_PROPERTYOBJECTSFILE__			"OBJECTSFILE"
#define __GAME_OBJECTSDEFINITIONSTDFILE__		"objects.xml"
#define __GAME_PROPERTYENTITIESFILE__			"ENTITIESFILE"
#define __GAME_ENTITIESDEFINITIONSSTDFILE__		"entities.xml"
#define __GAME_PROPERTYMOVEMENTSFILE__			"MOVEMENTSFILE"
#define __GAME_MOVEMENTSDEFINITIONSSTDFILE__	"movements.xml"
#define __GAME_PROPERTYSOUNDSFILE__				"SOUNDSFILE"
#define __GAME_SOUNDSDEFINITIONSTDFILE__		"sounds.xml"
#define __GAME_PROPERTYGUISYSTEMFILE__			"GUISYSTEMFILE"
#define __GAME_GUISYSTEMDEFINITIONSDFILE__		"guisystem.xml"
#define __GAME_PROPERTUCHARACTERMONITORFILE__	"CHRMONITOR"
#define __GAME_CHARACTERMONITORSTDFILE__		"monitor.xml"

#define __MININT__								std::numeric_limits<int>::lowest ()
#define __MAXINT__								std::numeric_limits<int>::max ()
#define __MINFLOAT__							std::numeric_limits<float>::lowest ()
#define __MAXFLOAT__							std::numeric_limits<float>::max ()
#define __MINBDATA__							std::numeric_limits<QGAMES::bdata>::lowest ()
#define __MAXBDATA__							std::numeric_limits<QGAMES::bdata>::max ()
#define __BD									(QGAMES::bdata)
#define __RANDOM__(x)							(rand () % x)
#define __1IN2PROBABLE__						(__RANDOM__(100) >= 50)
#define __1IN3PROBABLE__						(__RANDOM__(100) >= 66)
#define __2IN3PROBABLE__						(__RANDOM__(100) >= 33)
#define __1IN4PROBABLE__						(__RANDOM__(100) >= 75)
#define __3IN4PROBABLE__						(__RANDOM__(100) >= 25)
#define __1IN1000PROBABLE__						(__RANDOM__(1000) >= 999)

#define __NULL_STRING__							""
#define __YES_STRING__							"YES"
#define __NO_STRING__							"NO"

#define __QGAMES_MAINSCREEN__					0

#define __QGAMES_EVENTCOLLISION__				1
#define __QGAMES_EVENTONTILE__					2

#define __QGAMES_INCLUDENAME__					"Include"
#define __QGAMES_INCLUDEATTRFILE__				"file"

#define __QGAMES_FORMTAGNAME__					"Form"
#define __QGAMES_FORMATTRID__					"id"
#define __QGAMES_FORMATTRNAME__					"name"
#define __QGAMES_FORMATTRFILE__					"file"

// For sprites (2D)
#define __QGAMES_FORMATTRTYPE__					"type"
#define __QGAMES_FORMATTRWIDTH__				"width"
#define __QGAMES_FORMATTRHEIGHT__				"height"
#define __QGAMES_FORMATTRFRAMESPACING__			"fSpacing"
#define __QGAMES_FORMATTRFRAMEMARGIN__			"fMargin"
#define __QGAMES_FORMATTRFRAMEWIDTH__			"fWidth"
#define __QGAMES_FORMATTRFRAMEHEIGHT__			"fHeight"
#define __QGAMES_FORMATTRALPHACOLOR__			"aColor"
#define __QGAMES_FORMATATTRPRJTYPE__			"projectionType" // By default it is orthogonal (it is not a mandatory field)
#define __QGAMES_FORMATATTRADJUSTTYPE__			"adjustType"
#define __QGAMES_FORMATTRNUMBERFRAMES__			"nFrames"
#define __QGAMES_FORMATTRSPECIALFRAMEID__		"id"
#define __QGAMES_FORMATTRSPECIALFRAMEPOSX__		"fPosX"
#define __QGAMES_FORMATTRSPECIALFRAMEPOSY__		"fPosY"
#define __QGAMES_FORMATTRSPECIALFRAMEDFWIDTH__	"fWidth"
#define __QGAMES_FORMATTRSPECIALFRAMEDFHEIGHT__	"fHeight"
#define __QGAMES_FORMATTRSPECIALFRAMEXOFF__		"xoffset"
#define __QGAMES_FORMATTRSPECIALFRAMEYOFF__		"yoffset"
#define __QGAMES_FORMATTRSPECIALFRAMEWIDTH__	"width"
#define __QGAMES_FORMATTRSPECIALFRAMEHEIGHT__	"height"

// For 3d forms
#define __QGAMES_FORM3DARTICULATIONTAGNAME__	"Articulation"
#define __QGAMES_FORM3DARTIDATTRNAME__			"id"
#define __QGAMES_FORM3DARTPOSATTRNAME__			"position"
#define __QGAMES_FORM3DARTORATTRNAME__			"orientation"
#define __QGAMES_FORM3DMEMBERTAGNAME__			"Member"
#define __QGAMES_FORM3DMEMBERIDATTRNAME__		"id"
#define __QGAMES_FORM3DMEMBERPOSATTRNAME__		"position"
#define __QGAMES_FORM3DFACETAGNAME__			"Face"
#define __QGAMES_FORM3DFACEIDATTRNAME__			"id"
#define __QGAMES_FORM3DFACECOLORATTRNAME__		"color"
#define __QGAMES_FORM3DPOSITIONTAGNAME__		"Position"
#define __QGAMES_FORM3DPOSVALUEATTRNAME__		"value"
#define __QGAMES_FORM3DFRAMETAGNAME__			"Frame"
#define __QGAMES_FORM3DFRAMEIDATTRNAME__		"id"
#define __QGAMES_FORM3DTURNTAGNAME__			"Turn"
#define __QGAMES_FORM3DTURNIDATTRNAME__			"id"
#define __QGAMES_FORM3DTURNANGLEATTRNAME__		"angle"

#define __QGAMES_ENTITYTAGNAME__				"Entity"
#define __QGAMES_ENTITYATTRID__					"id"
#define __QGAMES_ENTITYFORMSBLOCK__				"Forms"
#define __QGAMES_ENTITYFORMSATTRID__			"id"
#define __QGAMES_ENTITYCAPACITIESBLOCK__		"Capacities"
#define __QGAMES_ENTITYCAPACITIESATTRID__		"id"
#define __QGAMES_ENTITYCAPACITIESATTRVALUE__	"value"
#define __QGAMES_ENTITYPHYSICSBLOCK__			"Physics"
#define __QGAMES_ENTITYPHYSICSATTRID__			"id"
#define __QGAMES_ENTITYPHYSICSATTRVALUE__		"value"
#define __QGAMES_ENTITYATTRSBLOCK__				"Attributes"
#define __QGAMES_ENTITYATTRATTRID__				"id"
#define __QGAMES_ENTITYATTRATTRVALUE__			"value"
#define __QGAMES_ENITYMOVEMENTSBLOCK__			"Movements"
#define __QGAMES_ENTITYMOVEMENTSATTRID__		"id"
#define __QGAMES_SETOFENTITIESTAGNAME__			"SetOfEntities"
#define __QGAMES_SETOFENTITIESATTRID__			"fromId"
#define __QGAMES_SETOFENTITIESATTRNUMBER__		"number"
#define __QGAMES_SETOFENTITIESFORMSBASEBLOCK__	"FormsBase"
#define __QGAMES_SETOFENTITIESMOVSBASEBLOCK__	"MovementsBase"
#define __QGAMES_ENTITYANIMATIONSBLOCK__		"Animations"
#define __QGAMES_ENTITYANIMATIONTAGNAME__		"Animation"
#define __QGAMES_ENTITYANIMATIONATTRID__		"id"
#define __QGAMES_ENTITYANIMATIONATTRTYPE__		"type"
#define __QGAMES_ENTITYANIMATIONNOANTYPE__		-1
#define __QGAMES_ENTITYANIMATIONFORMANTYPE__	0
#define __QGAMES_ENTITYANIMATIONEMPTYANTYPE__	1
#define __QGAMES_ENTITYANATTRFORM__				"FORM"
#define __QGAMES_ENTITYANATTRINITIALASPECT__	"INITIALASPECT"
#define __QGAMES_ENTITYANATTRFINALASPECT__		"FINALASPECT"
#define __QGAMES_ENTITYANATTRFRACTIONTOCHANGE__	"FRACTIONTOCHANGE"
#define __QGAMES_ENTITYANATTRCYCLIC__			"LOOP"
#define __QGAMES_ENTITYANATTRLINK__				"LINK"
#define __QGAMES_ENTITYANATTRDIRECTION__		"DIRECTION"
#define __QGAMES_ENTITYANATTRACCELERATION__		"ACCELERATION"
#define __QGAMES_ENTITYSTATESBLOCK__			"States"
#define __QGAMES_ENTITYSTATETAGNAME__			"State"
#define __QGAMES_ENTITYSTATEATTRID__			"id"
#define __QGAMES_ENTITYSTATEATTRANIMATION__		"animation"
#define __QGAMES_ENTITYSTATEATTRMOVEMENT__		"movement"
#define __QGAMES_ENTITYSTATEATTRMOVEMENTBASE__	"movementBase"
#define __QGAMES_ENTITYSTATEPRMDIRECTION__		"DIRECTION"
#define __QGAMES_ENTITYSTATEPRMACCELERATION__	"ACCELERATION"
#define __QGAMES_COMPOSITEENTITYTAGNAME__		"CompositeEntity"
#define __QGAMES_COMPOSITEENTITYATTRID__		"id"
#define __QGAMES_COMPOSITEENTYREFETYTAGNAME_	"RefEntity"
#define __QGAMES_COMPOSITEENTYREFETYATTRID__	"id"
#define __QGAMES_COMPOSITEENTYREFSETYTAGNAME__	"RefSetOfEntities"
#define __QGAMES_COMPOSITEENTYREFSETYATTRFROM__	"fromId"
#define __QGAMES_COMPOSITEENTYREFSETYATTRNUM__	"number"

#define __QGAMES_SOUNDTAGNAME__					"Sound"
#define __QGAMES_SOUNDATTRID__					"id"
#define __QGAMES_SOUNDATTRTYPE__				"type"
#define __QGAMES_SOUNDATTRLOOP__				"loop"
#define __QGAMES_SOUNDATTRFILE__				"file"

#define __QGAMES__MOVEMENTTAGNAME__				"Movement"
#define __QGAMES__MOVEMENTATTRID__				"id"
#define __QGAMES__MOVEMENTPARAMATTRID__			"id"
#define __QGAMES__MOVEMENTPARAMATTRVALUE__		"value"
#define __QGAMES__SETMOVEMENTSTAGNAME__			"SetOfMovements"
#define __QGAMES__SETMOVEMENTSATTRFROM__		"fromId"
#define __QGAMES__SETMOVEMENTSATTRNUMBER__		"number"
#define __QGAMES__SETOFMOVEMENTSATTRID__		"fromId"
#define __QGAMES__SETOFMOVEMENTSATTRNUMBER__	"number"

#define __QGAMES_ELEMENTSBLOCK__				"Element"
#define __QGAMES_ATTRSBLOCK__					"Attributes"
#define __QGAMES_IMAGEBLOCK__					"Image"
#define __QGAMES_BACKGROUNDBLOCK__				"Background"
#define __QGAMES_POLYLINEBLOCK__				"Polyline"
#define __QGAMES_POLYGONBLOCK__					"Polygon"
#define __QGAMES_ELLIPSEBLOCK__					"Ellipse"
#define __QGAMES_COMPOSITEBLOCK__				"Composite"
#define __QGAMES_POLYATTRID__					"id"
#define __QGAMES_POLYATTRCOLOR__				"color"
#define __QGAMES_POLYPOINTBLOCK__				"Point"
#define __QGAMES_POLYPTATTRX__					"X"
#define __QGAMES_POLYPTATTRY__					"Y"
#define __QGAMES_POLYPTATTRZ__					"Z"
#define __QGAMES_IMAGEATTRID__					"id"
#define __QGAMES_IMAGEATTRFORM__				"form"
#define __QGAMES_BKATTRID__						"id"
#define __QGAMES_BKATTRFORM__					"form"
#define __QGAMES_BKATTRTIMES__					"times"
#define __QGAMES_BKFADEGRADEATTR__				"FADEGRADE"
#define __QGAMES_BKAUTOMATICMOVEATTR__			"AUTOMATICMOVE"
#define __QGAMES_BKMOVDIRECTIONATTR__			"MOVDIRECTION"
#define __QGAMES_BKSPEEDPROPERTYATTR__			"SPEED"
#define __QGAMES_BKPIXELSATTR__					"PIXELS"
#define __QGAMES_BKLINKEDBKATTR__				"LINKEDBK"
#define __QGAMES_BKSPEEDLINKEDBKATTR__			"SPEEDLINKEDBK"
#define __QGAMES_BKROLLATTR__					"ROLL"
#define __QGAME_BKFIXPOSITIONATTR__				"FIX"
#define __QGAMES_ELLIPSEATTRID__				"id"
#define __QGAMES_ELLIPSEATTRVX__				"vX"
#define __QGAMES_ELLIPSEATTRVY__				"vY"
#define __QGAMES_ELLIPSEATTRVZ__				"vZ"
#define __QGAMES_ELLIPSEATTRR1__				"r1"
#define __QGAMES_ELLIPSEATTRR2__				"r2"
#define __QGAMES_ELLIPSEATTRCOLOR__				"color"
#define __QGAMES_COMPOSITEATTRID__				"id"
#define __QGAMES_COMPOSITEATTRX__				"X"
#define __QGAMES_COMPOSITEATTRY__				"Y"
#define __QGAMES_COMPOSITEATTRZ__				"Z"
#define __QGAMES_COMPOSITEELMNTATTRID__			"id"
#define __QGAMES_ATTRSATTRID__					"id"
#define __QGAMES_ATTRSATTRVALUE__				"value"

#define __QGAMES_GUISYSTEMTAGNAME__				"GUISystem"
#define __QGAMES_WIDGETTAGNAME__				"Widget"
#define __QGAMES_REFTOWIDGETTAGNAME__			"RefWidget"
#define __QGAMES_GUISYSTEMATTRID__				"id"
#define __QGAMES_GUISYSTEMATTRMAINWIDGET__		"main"
#define __QGAMES_WIDGETATTRID__					"id"
#define __QGAMES_WIDGETATTRTYPE__				"type"
#define __QGAMES_WIDGETATTRPOSITION__			"position"
#define __QGAMES_WIDGETATTRACTIVE__				"active"
#define __QGAMES_REFWIDGETATTRID__				"id"
#define __QGAMES_WIDGETATTRSTAGNAME__			"Attributes"
#define __QGAMES_WIDGETATTRTAGNAME__			"Attribute"
#define __QGAMES_WIDGETATTRSATTRID__			"id"
#define __QGAMES_WIDGETATTRSATTRVALUE__			"value"
#define __QGAMES_WIDGETDECORATORTAGNAME__		"Decorator"
#define __QGAMES_WIDGETDECORATORATTRTYPE__		"type"
#define __QGAMES_WIDGETDECORATORATTRSTAGNAME__	"Attributes"
#define __QGAMES_WIDGETDECORATORATTRTAGNAME__	"Attribute"
#define __QGAMES_WIDGETDECORATORATTRID__		"id"
#define __QGAMES_WIDGETDECORATORATTRVALUE__		"value"

#define __QGAMES_RESOURCEGROUPTAGNAME__			"ResourceGroup"
#define __QGAMES_RESOURCEGROUPATTRID__			"id"
#define __QGAMES_RESOURCEFORMSTAGNAME__			"Forms"
#define __QGAMES_RESOURCESOUNDSTAGNAME__		"Sounds"
#define __QGAMES_RESOURCEMOVSTAGNAME__			"Movements"
#define __QGAMES_RESOURCEENTITIESTAGNAME__		"Entities"
#define __QGAMES_RESOURCEOBJSTAGNAME__			"Objects"

#define __QGAMES_MASKTAGNAME__					"Mask"
#define __QGAMES_MASKATTRID__					"id"
#define __QGAMES_MASKATTRBLENDINGTYPE__			"type"
#define __QGAMES_MASKATTRTYPE__					"blendingType"
#define __QGAMES_MASKATTRWIDTH__				"width"
#define __QGAMES_MASKATTRHEIGHT__				"height"
#define __QGAMES_MASKPARAMETERTAGNAME__			"Parameter"
#define __QGAMES_MASKPARAMATTRID__				"id"
#define __QGAMES_MASKPARAMATTRVALUE__			"value"
#define __QGAMES_MASKTYPEINCIRCLE__				0
#define __QGAMES_MASKTYPEOUTCIRCLE__			1
#define __QGAMES_MASKTYPELEFTZONE__				2
#define __QGAMES_MASKTYPERIGHTZONE__			3
#define __QGAMES_MASKTYPEUPZONE__				4
#define __QGAMES_MASKTYPEDOWNZONE__				5
#define __QGAMES_MASKTYPEINCIRCLEGEN__			6
#define __QGAMES_MASKTYPEOUTCIRCLEGEN__			7
#define __QGAMES_CIRCLEMASKRADIXATTR__			"radix"
#define __QGAMES_CIRCLEMASKPOSATTR__			"position"
#define __QGAMES_CIRCLEMASKCOLORATTR__			"color"
#define __QGAMES_ZONEMASKLENGTHATTR__			"distance"
#define __QGAMES_ZONEMASKCOLORATTR__			"color"

#define __QGAMES_ROUNDINGDECORATORTYPE__		0

#define __QGAMES_BASICCOMPOSITEWIDGETTYPE__		0
#define __QGAMES_LABELWIDGETTYPE__				1
#define __QGAMES_INTROWIDGETTYPE__				2
#define __QGAMES_ITERATINGLABELWIDGETTYPE__		3
#define __QGAMES_ITERATINGLABELWIDGETKEYTYPE__	4

#define __QGAMES_ROUNDDECATTRCOLORROUND__		"ColorBox"
#define __QGAMES_ROUNDDECATTRTHICKNESS__		"Thickness"
#define __QGAMES_ROUNDDECATTRCOLORINSIDE__		"ColorInside"
#define __QGAMES_ROUNDDECATTRSEPARATION__		"Separation"

#define __QGAMES_BLINKINGBKDECATTRBACKCOLOR__	"ColorBackground"
#define __QGAMES_BLINKINGBKDECATTRSEPARATION__	"Separation"
#define __QGAMES_BLINKINGBKDECATTRINIFADE__		"InitialFade"
#define __QGAMES_BLINKINGBKDECATTRFINALFADE__	"FinalFade"
#define __QGAMES_BLINKINGBKDECATTRFADEGROWTH__	"FadeGrowth"

#define __QGAMES_LABELWIDGETATTRFORM__			"Form"
#define __QGAMES_LABELWIDGETATTRBASECHR__		"BaseChr"
#define __QGAMES_LABELWIDGETATTRALPHAON__		"AlphaOn"
#define __QGAMES_LABELWIDGETATTRALPHAOFF__		"AlphaOff"
#define __QGAMES_LABELWIDGETATTRPIXELSAMONG__	"PixelsAmong"
#define __QGAMES_LABELWIDGETATTRDIRECTION__		"Direction"
#define __QGAMES_LABELWIDGETATTRDIRHR__			"HORIZONTALRIGHT"
#define __QGAMES_LABELWIDGETATTRDIRHL__			"HORIZONTALLEFT"
#define __QGAMES_LABELWIDGETATTRDIRVD__			"VERTICALDOWN"
#define __QGAMES_LABELWIDGETATTRDIRVU__			"VERTICALUP"
#define __QGAMES_LABELWIDGETATTRTEXT__			"Text"

#define __QGAMES_ITERLABELWIDGETATTRSTRVALUES__	"StringValues"
#define __QGAMES_ITERLABELWIDGETATTRINTVALUES__	"IntValues"

#define __QGAMES_INTROWIDGETATTRFORM__			"Form"
#define __QGAMES_INTROWIDGETATTRBASECHR__		"BaseChr"
#define __QGAMES_INTROWIDGETATTRALPHAON__		"AlphaOn"
#define __QGAMES_INTROWIDGETATTRALPHAOFF__		"AlphaOff"
#define __QGAMES_INTROWIDGETATTRPIXELSAMONG__	"PixelsAmong"
#define __QGAMES_INTROWIDGETATTRNUMBERCHARS__	"Chars"
#define __QGAMES_INTROWIDGETATTRMASK__			"Mask"
#define __QGAMES_INTROWIDGETATTRCURSORCOLOR__	"CursorColor"
#define __QGAMES_INTROWIDGETATTRLOCATION__		"Location"
#define __QGAMES_INTROWIDGETATTRLOCATIONR__		"RIGHT"
#define __QGAMES_INTROWIDGETATTRLOCATIOND__		"DOWN"
#define __QGAMES_INTROWIDGETATTRTEXT__			"Text"

#define __QGAMES_MONITORTAGNAME__				"Monitor"
#define __QGAMES_MONITOATTRID__					"id"
#define __QGAMES_MONITORATTRCYCLIC__			"cyclic"
#define __QGAMES_MONITORSTEPTAGNAME__			"Step"
#define __QGAMES_MONITORSTEPATTRTYPE__			"type"
#define __QGAMES_MONITORVARIBLESTAGNAME__		"Variables"
#define __QGAMES_MONITORVARIABLETAGNAME__		"Variable"
#define __QGAMES_MONITORVARIABLEATTRID__		"id"
#define __QGAMES_MONITORVARIABLEATTRVALUE__		"value"
#define __QGAMES_MONITORCOMPLEXSTEPTAGNAME__	"ComplexStep"
#define __QGAMES_MONITORCOMPLEXSTEPATTRTYPE__	"type"

#define __QGAMES_STDTYPEFORMSLOADER__			"Forms"
#define __QGAMES_STDTYPESOUNDSLOADER__			"Sounds"
#define __QGAMES_STDTYPEMOVEMENTSLOADER__		"Movements"
#define __QGAMES_STDTYPEOBJECTSLOADER__			"Objects"
#define __QGAMES_STDTYPEENTITIESLOADER__		"Entities"

#define __QGAMES_GAMESTATETAGNAME__				"GameState"
#define __QGAMES_GAMESTATEATTRID__				"id"
#define __QGAMES_GAMESTATEATTRMAIN__			"main"
#define __QGAMES_GAMESTATESTTRTYPE__			"type"
#define __QGAMES_GAMESTATEATTRNAME__			"name"
#define __QGAMES_GAMESTATEATTRSBLOCK__			"Attributes"
#define __QGAMES_GAMESTATEATTRTAGNAME__			"Attribute"
#define __QGAMES_GAMESTATEATTRATTRID__			"id"
#define __QGAMES_GAMESTATEATTRATTRVALUE__		"value"
#define __QGAMES_GAMESTATENESTEDBLOCK__			"Nested"
#define __QGAMES_GAMESTATEFLOWBLOCK__			"FlowConditions"
#define __QGAMES_GAMESTATEFLOWATTRON__			"on"
#define __QGAMES_GAMESTATEFLOWATTRCONDITION__	"when"
#define __QGAMES_GAMESTATEFLOWATTRTO__			"to"

#define __QGAMES_GAMESTATETYPEEXITTYPE__		7000
#define __QGAMES_GAMESTATETYPECONTROLTYPE__		7001

#define __QGAMES_MOVEJOYSTICKEVENT__			7000
#define __QGAMES_BUTTONJOYSTICKEVENT__			7001
#define __QGAMES_KEYBOARDEVENT__				7002
#define __QGAMES_MOUSEMOVEMENTEVENT__			7003
#define __QGAMES_MOUSEBUTTONEVENT__				7004
#define __QGAMES_LOOPCOUNTEREVENT__				7005
#define __QGAMES_MOVEMENTNOTPOSSIBLE__			7006

#define __QGAMES_WIDGETGETFOCUSEVENT__			7010
#define __QGAMES_WIDGETLOSESFOCUSEVENT__		7011
#define __QGAMES_WIDGETSELECTEDEVENT__			7012

#define __QGAMES_CHRSTEPSMONITORFIRSTSTEP__		7013
#define __QGAMES_CHRSTEPSMONITORLASTSTEP__		7014
#define __QGAMES_CHRSTEPSMONITORSTARTSBACK__	7015
#define __QGAMES_CHRSTEPSMONITOROTHERSTEP__		7113

#define __QGAMES_GAMENESTEDSTATEFINISHED__		7016

#define __QGAMES_POSITIONCHANGED__				7200

#define __QGAMES_CHANGESTATEBUOY__				7000

#define __QGAMES_CHRSTEPNONE__					0
#define __QGAMES_CHRSTEPTIME__					1
#define __QGAMES_CHRSTEPTIMEATTRTIME__			"Time"
#define __QGAMES_CHRSTEPTIMEDEFAULTTIME__		__BD 1.0 // seconds
#define __QGAMES_CHRSTEPWAITFORSTATE__			2
#define __QGAMES_CHRSTEPWAITFORSTATEATTRSTATE__	"State"
#define __QGAMES_CHRSTEPWAITFORSTATEDEFSTATE__	0 // It could generate an error when execute (it couldn't exist)
#define __QGAMES_CHRSTEPCHANGESTATE__			3
#define __QGAMES_CHRSTEPCHANGESTATEATTRSTATE__	"State"
#define __QGAMES_CHRSTEPCHANGESTATEDEFSTATE__	0 // It could generate an error when execute (it couldn't exist)
#define __QGAMES_CHRSTEPJUSTMOVESTATE__			4
#define __QGAMES_CHRSTEPMOVESTATE__				5
#define __QGAMES_CHRSTEPMOVSTATEATTRDIR__		"Direction"
#define __QGAMES_CHRSTEPMOVSTATEDEFDIR__		"1,0,0"
#define __QGAMES_CHRSTEPMOVSTATEATTRACCL__		"Acceleration"
#define __QGAMES_CHRSTEPMOVDEFACCL__			"0,0,0"
#define __QGAMES_CHRSTEPDISTANCE__				6
#define __QGAMES_CHRSTEPDISTANCEATTRDISTANCE__	"Distance"
#define __QGAMES_CHRSTEPDISTANCEDEFDISTANCE__	10 // pixels
#define __QGAMES_CHRSTEPRANDOMTIME__			7
#define __QGAMES_CHRSTEPNEARDISTANCE__			8
#define __QGAMES_CHRSTEPNEARDISTANCEATTRPOINT__	"Point"
#define __QGAMES_CHRSTEPNEARDISTANCEATTRERROR__	"Distance"
#define __QGAMES_CHRSTEPNEARDISTANCEDEFPOINT__	"0,0,0"
#define __QGAMES_CHRSTEPNEARDISTANCEDEFERROR__	10 // pixels
#define __QGAMES_CHRSTEPLIMITS__				9
#define __QGAMES_CHRSTEPLIMITSATTRLIMITS__		"Limits"
#define __QGAMES_CHRSTEPLIMITSDEFLIMITS1__		"0,0,0,0,0,0,0,0,1" // Corner1, Corner2, Plane Vector
#define __QGAMES_CHRSTEPLIMITSATTRDISTANCE__	"Distance"
#define __QGAMES_CHRSTEPLIMITSDEFDISTANCE__		10 // pixels
#define __QGAMES_CHRCOMPLEXSTEPSEQUENTIAL__		20
#define __QGAMES_CHRCOMPLEXSTEPRANDOM__			21
#define __QGAMES_CHRCOMPLEXSTEPCYCLIC__			22

#define __QGAMES_COMMSTAGNAME__					"Communication"
#define __QGAMES_COMMSATTRID__					"id"
#define __QGAMES_COMMSATTRTYPE__				"type"
#define __QGAMES_COMMSATTRSBLOCK__				"Attributes"
#define __QGAMES_COMMSATTRATTRID__				"id"
#define __QGAMES_COMMSATTRATTRVALUE__			"value"
#define __QGAMES_COMMSCHANNELNOTHING__			"NOTHING"
#define __QGAMES_COMMSCHANNELCONSOLELOG__		"CONSOLELOG"
#define __QGAMES_COMMSCHANNELFILELOG__			"FILELOG"
#define __QGAMES_COMMSCHANNELFILELOGFNAME__		"FNAME"
#define __QGAMES_COMMSCHANNELDEFFILELOGNAME__	"LOG.log"

#define __QGAMES_DEFAULTCAMERAID__				"DEFAULTCAMERA"
#define __QGAMES_MAINCAMERAID__					"MAINCAMERA"

#define __QGAMES_EXITGAMEGAMESTATE__			7000
#define __QGAMES_EXITGAMEGAMESTATENAME__		"7000"

// Runtime values structure...
#define __QGAMES_RUNTIMEVALUESELMNTTYPE__		"ELMNT" // Very generic...
#define __QGAMES_RUNTIMEVALUESCOUNTERSTYPE__	"COUNTERS"
#define __QGAMES_RUNTIMEVALUESCOUNTERTYPE__		"COUNTER"
#define __QGAMES_RUNTIMEVALUESSWITCHESTYPE__	"SWITCHES"
#define __QGAMES_RUNTIMEVALUESSWITCHTYPE_		"SWITCH"
#define __QGAMES_RUNTIMEVALUESANIMATIONTYPE__	"ANIMATION"
#define __QGAMES_RUNTIMEVALUESSTATETYPE__		"STATE"
#define __QGAMES_RUNTIMEVALUESCHRMONITORTYPE__	"CHRMONITOR"
#define __QGAMES_RUNTIMEVALUESCHRSTEPTYPE__		"CHRSTEP"
#define __QGAMES_RUNTIMEVALUESCHRSTEPSTYPE__	"CHRSTEPS"
#define __QGAMES_RUNTIMEVALUESENTITIESTYPE__	"ENTITIES"
#define __QGAMES_RUNTIMEVALUESENTITYMOVTYPE__	"MOV"
#define __QGAMES_RUNTIMEVALUESOTHERPRPSTYPE__	"PRPS"

#endif
  
// End of the file
/*@}*/
