/** \ingroup DWTheRevege */
/*@{*/

/**	
 *	@file	
 *	File: Defs.hpp \n
 *	Framework: Dragonwind II (the revenge) \n
 *	Author: Ignacio Cea Fornies (Community Networks) \n
 *	Creation Date: 24/01/2020 \n
 *	Description: Defines and general includes of Dragonwind II Game
 *	Versions: 1.0 Initial
 */

#ifndef __DRAGONWINDTHEREVENGE_DRAGONWINDGAMEDEFINES__
#define __DRAGONWINDTHEREVENGE_DRAGONWINDGAMEDEFINES__

#include <DragonwindLike/dwdefinitions.hpp>

// A standard configuration parameter to declare the number of lives
#define __DRAGONWINDTHEREVENGE_MAXNUMBEROFLIVESPARAMETER__			"LIVES"
#define __DRAGONWINDTHEREVENGE_DEFAULTMAXNUMBEROFLIVESPARAMETER__	"3"
// same related with showing or not the FPS
#define __DRAGONWINDTHEREVENGE_SHOWFPSPARAMETER__					"FPS"
#define __DRAGONWINDTHEREVENGE_DEFAULTSHOWFPSPARAMETER__			"NO"

// Actions block to control lisft
#define __DRAGONWINDTHEREVENTE_LIFTACTIONBLOCKBASEID__				80000
#define __DRAGONWINDTHEREVENGE_LIFTACTIONBLOCKNUMBER__				10
#define __DRAGONWINDTHEREVENGE_LIFTACTIONBLOCKLIFTLISTPARAMID__		"Lifts"

// The city world
#define __DRAGONWINDTHEREVENGE_CITYWORLDID__						50001
#define __DRAGONWINDTHEREVENGE_CITYWORLDBACKGROUNDMAPID__			__DRAGONWIND_CITYBKMAPID__
#define __DRAGONWINDTHEREVENGE_CITYWORLDSCENE0ID__					60002
#define __DRAGONWINDTHEREVENGE_CITYWORLDSCENE0MAPID__				60002
#define __DRAGONWINDTHEREVENGE_CITYWORLDSCENE1ID__					60003
#define __DRAGONWINDTHEREVENGE_CITYWORLDSCENE1MAPID__				60003
#define __DRAGONWINDTHEREVENGE_CITYWORLDSCENE2ID__					60004
#define __DRAGONWINDTHEREVENGE_CITYWORLDSCENE2MAPID__				60004
#define __DRAGONWINDTHEREVENGE_CITYWORLDSCENE3ID__					60005
#define __DRAGONWINDTHEREVENGE_CITYWORLDSCENE3MAPID__				60005
#define __DRAGONWINDTHEREVENGE_CITYWORLDSCENE4ID__					60006
#define __DRAGONWINDTHEREVENGE_CITYWORLDSCENE4MAPID__				60006

// The landscape world
#define __DRAGONWINDTHEREVENGE_LANDSCAPEWORLDID__					50002
#define __DRAGONWINDTHEREVENGE_LANDSCAPEWORLDBACKGROUNDMAPID__		__DRAGONWIND_LANDSCAPEBKMAPID__
#define __DRAGONWINDTHEREVENGE_LANDSCAPEWITHCAVEWORLDBKMAPID__		80130
#define __DRAGONWINDTHEREVENGE_CAVEWORLDBKMAPID__					80136
#define __DRAGONWINDTHEREVENGE_LANDSCAPEWORLDSCENE0ID__				70000
#define __DRAGONWINDTHEREVENGE_LANDSCAPEWORLDSCENE0MAPID__			70000
#define __DRAGONWINDTHEREVENGE_LANDSCAPEWORLDSCENE1ID__				70001
#define __DRAGONWINDTHEREVENGE_LANDSCAPEWORLDSCENE1MAPID__			70001
#define __DRAGONWINDTHEREVENGE_LANDSCAPEWORLDSCENE1GORILLAABID__	50009
#define __DRAGONWINDTHEREVENGE_LANDSCAPEWORLDSCENE2ID__				70002
#define __DRAGONWINDTHEREVENGE_LANDSCAPEWORLDSCENE2MAPID__			70002
#define __DRAGONWINDTHEREVENGE_LANDSCAPEWORLDSCENE3ID__				70003
#define __DRAGONWINDTHEREVENGE_LANDSCAPEWORLDSCENE3MAPID__			70003
#define __DRAGONWINDTHEREVENGE_LANDSCAPEWORLDSCENE4ID__				70004
#define __DRAGONWINDTHEREVENGE_LANDSCAPEWORLDSCENE4MAPID__			70004

// The darkforest world
#define __DRAGONWINDTHEREVENGE_DARKFORESTWORLDID__					50003
#define __DRAGONWINDTHEREVENGE_DARKFORESTWORLDBACKGROUNDMAPID__		__DRAGONWIND_DARFORESTBKMAPID__
#define __DRAGONWINDTHEREVENGE_DARKFORESTWORLDSCENE0ID__			80000
#define __DRAGONWINDTHEREVENGE_DARKFORESTWORLDSCENE0MAPID__			80000
#define __DRAGONWINDTHEREVENGE_DARKFORESTWORLDSCENE1ID__			80001
#define __DRAGONWINDTHEREVENGE_DARKFORESTWORLDSCENE1MAPID__			80001
#define __DRAGONWINDTHEREVENGE_DARKFORESTWORLDSCENE2ID__			80002
#define __DRAGONWINDTHEREVENGE_DARKFORESTWORLDSCENE2MAPID__			80002

// The dessert (or mountains) as you want
#define __DRAGONWINDTHEREVENGE_MOUNTAINSWORLDID__					50004
#define __DRAGONWINDTHEREVENGE_MOUNTAINSWORLDBACKGROUNDMAPID__		__DRAGONWIND_MOUNTAINSBKMAPID__
#define __DRAGONWINDTHEREVENGE_MOUNTAINSWORLDLARGEWORLDBKMAPID__	80140
#define __DRAGONWINDTHEREVENGE_MOUNTAINSWORLDSCENE0ID__				90000
#define __DRAGONWINDTHEREVENGE_MOUNTAINSWORLDSCENE0MAPID__			90000
#define __DRAGONWINDTHEREVENGE_MOUNTAINSWORLDSCENE1ID__				90001
#define __DRAGONWINDTHEREVENGE_MOUNTAINSWORLDSCENE1MAPID__			90001
#define __DRAGONWINDTHEREVENGE_MOUNTAINSWORLDSCENE2ID__				90002
#define __DRAGONWINDTHEREVENGE_MOUNTAINSWORLDSCENE2MAPID__			90002
#define __DRAGONWINDTHEREVENGE_MOUNTAINSWORLDSCENE2ABLOCKID__		900021
#define __DRAGONWINDTHEREVENGE_MEORLDSSCENE2BLOCKSECPARAMID__		"SecondsToGoBack"
#define __DRAGONWINDTHEREVENGE_MOUNTAINSWORLDSCENE3ID__				90003
#define __DRAGONWINDTHEREVENGE_MOUNTAINSWORLDSCENE3MAPID__			90003
#define __DRAGONWINDTHEREVENGE_MOUNTAINSWORLDSCENE4ID__				90004
#define __DRAGONWINDTHEREVENGE_MOUNTAINSWORLDSCENE4MAPID__			90004

// The temple world
#define __DRAGONWINDTHEREVENGE_TEMPLEWORLDID__						50005
#define __DRAGONWINDTHEREVENGE_TEMPLEWORLDBACKGROUNDMAPID__			__DRAGONWIND_TEMPLEBKMAPID__
#define __DRAGONWINDTHEREVENGE_TEMPLEWORLDSCENE0ID__				100000
#define __DRAGONWINDTHEREVENGE_TEMPLEWORLDSCENE0MAPID__				100000
#define __DRAGONWINDTHEREVENGE_TEMPLEWORLDSCENE1ID__				100001
#define __DRAGONWINDTHEREVENGE_TEMPLEWORLDSCENE1MAPID__				100001
#define __DRAGONWINDTHEREVENGE_TEMPLEWORLDSCENE2ID__				100002
#define __DRAGONWINDTHEREVENGE_TEMPLEWORLDSCENE2MAPID__				100002

// Type of additional things to catch...
#define __DRAGONWINDTHEREVENGE_NINJATHINGHAMMERTYPE__				8
#define __DRAGONWINDTHEREVENGE_NINJATHINGKEYTYPE__					9
#define __DRAGONWINDTHEREVENGE_NINJATHINGLIGHTTYPE__				10

// Type of standard shootings
#define __DRAGONWINDTHEREVENGE_BALLOFFIRETYPE__						21

// The specific entities
#define __DRAGONWIND_DINOTYPEID__									4
#define __DRAGONWIND_MALEZOMBIETYPEID__								5
#define __DRAGONWIND_FEMALEZOMBIETYPEID__							6
#define __DRAGONWIND_KONGTYPEID__									7
#define __DRAGONWIND_ORCUSTYPEID__									8
#define __DRAGONWIND_BOARTYPEID__									9

// Flock of vultures
#define __DRAGONWINDTHEREVENGE_VULTUREBASEID__						60000
#define __DRAGONWINDTHEREVENGE_FLOACKOFVULTUREBASE__				60120
#define __DRAGONWINDTHEREVENGE_VULTUREFLYMOVEMENTBASEID__			70000
#define __DRAGONWINDTHEREVENGE_VULTURESTANDMOVEMENTBASEID__			70010
// Flock of wasps
#define __DRAGONWINDTHEREVENGE_WASPBASEID__							61000
#define __DRAGONWINDTHEREVENGE_FLOACKOFWASPBASE__					61120
#define __DRAGONWINDTHEREVENGE_WASPFLYMOVEMENTBASEID__				71000
#define __DRAGONWINDTHEREVENGE_WASPSTANDMOVEMENTBASEID__			71010
// Flock of bats
#define __DRAGONWINDTHEREVENGE_BATBASEID__							62000
#define __DRAGONWINDTHEREVENGE_FLOACKOFBATBASE__					62120
#define __DRAGONWINDTHEREVENGE_BATFLYMOVEMENTBASEID__				72000
#define __DRAGONWINDTHEREVENGE_BATSTANDMOVEMENTBASEID__				72010

// Sounds
#define __DRAGONWINDTHEREVENGE_OPENDOORSOUNDID__					80000
#define __DRAGONWINDTHEREVENGE_BEEWASPSSOUNDID__					80007
#define __DRAGONWINDTHEREVENGE_BATSSOUNDID__						80008
#define __DRAGONWINDTHEREVENGE_VULTURESSOUNDID__					80009

// Action Blocks
// Flock of Vultures
#define __DRAGONWINDTHEREVENGE_ACTIONBLOCKFMONSTERTYPEVULTURE__		2
#define __DRAGONWINDTHEREVENGE_ACTIONBLOCKFMONSTERTYPEWASP__		3
#define __DRAGONWINDTHEREVENGE_ACTIONBLOCKFMONSTERTYPEBAT__			4

#endif
  
// End of the file
/*@}*/